<?xml version="1.0" encoding="UTF-8"?>
<testrun name="PersonListPanelTest" project="MMI" tests="3" started="3" failures="1" errors="0" ignored="0">
  <testsuite name="task2and3.PersonListPanelTest" time="5.673">
    <testcase name="testNewPerson" classname="task2and3.PersonListPanelTest" time="2.59">
      <failure>junit.framework.AssertionFailedError: expected:&lt;task2and3.Person@6691177&gt; but was:&lt;task2and3.Person@5bf99eea&gt;
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:74)
	at task2and3.PersonListPanelTest.testNewPerson(PersonListPanelTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.extensions.jfcunit.JFCTestCase$5.run(JFCTestCase.java:580)
	at junit.extensions.jfcunit.JFCTestCase$3.run(JFCTestCase.java:478)
	at java.lang.Thread.run(Thread.java:680)

</failure>
    </testcase>
    <testcase name="testRemovePerson" classname="task2and3.PersonListPanelTest" time="1.158"/>
    <testcase name="testListSelection" classname="task2and3.PersonListPanelTest" time="1.923"/>
  </testsuite>
</testrun>
